# Local development — points at staging First Data endpoints
# VM args: -Denv=local -DmasterKey=localkey

sys-firstdata:
  http-listener:
    port: "8081"
    path: "/sys/firstdata/v1/*"

sys-firstdata-api:
  http-listener:
    autodiscovery-id: "0"

sys:
  server:
    hosts: "staging1.datawire.net:443,staging2.datawire.net:443"
  default-server-host: "staging1.datawire.net"
  path-suffix: "sd"
  service-id: "104"
  request-version: "3"
  application-version: "V001000"
  payload-encoding: "datawire"
  transaction-prefix: "SV."
  field-separator: "|1C"
  user-agent: "vxnapi_xml_3_2_0_19"
  timeout-responses: "205,8"
  invalidate-cache-responses: "8"
  url-cache-ttl: "300"
  whitelisted-brands: "yankee candle,marmot"
  app-id: "NWLECOMMWGIFTXML"
  tid: "00000000002"

marmot:
  terminal-id: "0002"
  merchant-key-id: "NOKEY"
  source-code: "30"
  activate-promo-code: "79234"

yankee-candle:
  terminal-id: "0001"
  merchant-key-id: "1002"
  source-code: "30"
  activate-promo-code: "30253"

notification:
  enabled: "false"
