#%RAML 1.0 NamedExample

value:
  errorType: APIKIT:NOT_IMPLEMENTED
  description : Not Implemented. This status code is received when the web server does not support the facility required.
  transaction-id: dd960082-abbf-47c2-8c65-f18eeb35848b