name: Mulesoft API

### Controls when the workflow will run
on:
  push:
    branches: [ "develop","master"]

jobs:
  int-mulesoft-api:
    uses: NewellBrands/SFRA-common-reusable-workflows/.github/workflows/mulesoft-build-deploy-aws.yml@main
    with:
      cloud_ver: 1
      worker: 1
      vcore: 0.1
    secrets: inherit
