#%RAML 1.0 DataType
type: object
properties: 
  file-path:
    required: true
    type: string
  file-name:
    required: true
    type: string
  target-systems:
    required: true
    type: string[]
  brands:
    required: true
    type: string[]