#%RAML 1.0 Trait
displayName: client-credentials

headers:
  client_id:
    description: Client Id
    required: true
    type: string
    example: 7b404180fbb84b099179a4126a9576ff
  client_secret:
    description: Client Secret
    required: true
    type: string
    example: e241f4aa3eca4b2a8FA67A2FEF5754F8
responses:
  401:
    description: Unauthorized or invalid client application credentials
  500:
    description: Bad response from authorization server, or WSDL SOAP Fault error
